config/routes.rb
Pm::Application.routes.draw do
  devise_for :users

  resources :projects do
    resources :tasks, only: [:index, :new, :create]
  end

  resources :tasks, only: [] do
    patch :assign, on: :member
  end

  root 'projects#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can [:read, :create], Project
    can [:update, :destroy], Project, owner: user
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :owner, class_name: User
  has_many   :tasks

  validates :name, length: { in: 4..30 }
  validates :owner, presence: true

  accepts_nested_attributes_for :tasks, allow_destroy: true

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :assignee, class_name: User
  belongs_to :project

  validates_presence_of :name, :description

  delegate :email, to: :assignee, prefix: true, allow_nil: true

  alias_attribute :title, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects, foreign_key: :owner_id
  has_many :tasks, foreign_key: :assignee_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  load_and_authorize_resource param_method: :project_params

  def index
    @projects = Project.includes(:owner)
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = current_user.projects.new(project_params)
    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  private
    
    def project_params
      params.require(:project).permit(:name, tasks_attributes: task_params)
    end

    def task_params
      [:id, :description, :due_date, :_destroy, :assignee_id, :name]
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :find_project, except: [:assign]

  def assign
    @task = Task.find(params[:id])
    @task.update_column(:assignee_id, current_user.id)
    redirect_to project_tasks_path(@task.project)
  end

  def index
    @tasks = @project.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to project_tasks_path(@project)
    else
      render :new
    end
  end

  private

  def find_project
    @project = Project.find(params[:project_id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :assignee_id, :due_date)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pm" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Pm</a>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>

app/views/projects/_form.html.erb
<%= simple_nested_form_for @project do |f| %>
  <%= f.input :name %>
  <%= f.fields_for :tasks do |task_form| %>
    <% if task_form.object.new_record? %>
      <%= task_form.association :assignee, label_method: :email, value_method: :id %>
      <%= task_form.input :name %>
      <%= task_form.input :description, as: :text %>
      <%= task_form.input :due_date %>
      <%= task_form.link_to_remove "Remove this task" %>
    <% end %>
  <% end %>
  <p><%= f.link_to_add "Add a task", :tasks %></p>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th><%= Project.human_attribute_name(:name) %></th>
      <th><%= Project.human_attribute_name(:owner) %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |p| %>
      <tr>
        <td><%= link_to p.name, project_path(p) %></td>
        <td><%= p.owner.email %></td>
        <td>
          <% if can? :update, p %>
            <%= link_to 'Edit', edit_project_path(p) %> | 
          <% end %>
          <% if can? :destroy, p %> 
            <%= link_to 'delete', project_path(p), method: :delete, data: { confirm: 'sure?' } %> |
          <% end %>
          <%= link_to 'tasks', project_tasks_path(p) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New', new_project_path, class: 'btn' %>

app/views/projects/show.html.erb
<h1> Project </h1>
<b><%= @project.name %></b>
<p><%= @project.owner.email %></p>
<h1> Tasks </h1>
<table class='table'>
  <% @project.tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= task.due_date %></td>
      <td><%= task.assignee_email %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'All projects', projects_path %>

app/views/tasks/_form.html.erb
<%= simple_nested_form_for [@project, @task] do |f| %>
  <%= f.association :assignee, label_method: :email, value_method: :id %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :due_date %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1> Tasks </h1>
<table class='table'>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= task.title %></td>
      <td><%= task.description %></td>
      <td><%= task.due_date %></td>
      <td><%= task.assignee_email %></td>
      <td><%= link_to 'assign to me', assign_task_path(task), method: :patch %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Create new task', new_project_task_path(@project), class: 'btn' %>
<p>
<%= link_to 'Go to projects page', projects_path %>
</p>

app/views/tasks/new.html.erb
<%= render 'form' %>